// Generated by React Router

import 'react-router';

declare module 'react-router' {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
  }
}

type Pages = {
  '/': {
    params: {};
  };
  '/about': {
    params: {};
  };
  '/postcard/:id': {
    params: {
      id: string;
    };
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page: '/' | '/about' | '/postcard/:id';
  };
  'routes/_index.tsx': {
    id: 'routes/_index';
    page: '/';
  };
  'routes/about.tsx': {
    id: 'routes/about';
    page: '/about';
  };
  'routes/postcard/$id.tsx': {
    id: 'routes/postcard/$id';
    page: '/postcard/:id';
  };
};
