// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/create-post": {
    params: {};
  };
  "/edit-post/:id": {
    params: {
      "id": string;
    };
  };
  "/postcard/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/create-post" | "/edit-post/:id" | "/postcard/:id";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/create-post.tsx": {
    id: "routes/create-post";
    page: "/create-post";
  };
  "routes/postcard/edit.tsx": {
    id: "routes/postcard/edit";
    page: "/edit-post/:id";
  };
  "routes/postcard/$id.tsx": {
    id: "routes/postcard/$id";
    page: "/postcard/:id";
  };
};